name: Go Test + Build + Docker

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'   # importante: solo 1.24, no 1.24.1 ni otra

      - name: Verificar versión Go
        run: go version     # Esto confirma qué versión está usando realmente

      - name: Ejecutar tests
        run: go test ./... -v

      - name: Cache de módulos Go
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Construir imagen Docker
        run: docker build -t sistema-tours .

      # Opcional: Ejecutar contenedor en el runner (no recomendado en prod)
      - name: Ejecutar contenedor Docker
        run: |
          docker stop sistema-tours || true
          docker rm sistema-tours || true
          docker run -d --name sistema-tours -p 8080:8080 sistema-tours
