name: Go Test + Build + Docker

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v3


        

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'   # importante: solo 1.24, no 1.24.1 ni otra
          check-latest: true


      - name: Verificar versi贸n Go
        run: go version

      - name: Mostrar variables de entorno relevantes
        run: env | grep -E 'GOPATH|GOROOT|GO'

      - name: Ejecutar tests
        run: go test ./... -v

      # Cache comentado para forzar run limpio
      # - name: Cache de m贸dulos Go
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cache/go-build
      #       ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v3

      - name: Construir imagen Docker
        run: docker build -t sistema-tours .

      - name: Ejecutar contenedor Docker
        run: |
          docker stop sistema-tours || true
          docker rm sistema-tours || true
          docker run -d --name sistema-tours -p 8080:8080 sistema-tours
